spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.butoube.com/:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  mvc:
    pathmatch:
      use-suffix-pattern: true


server:
  port: 80
  servlet:
    context-path: /
  path: "*.html"
logging:
  level:
    com.bguo: INFO